settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: holo-back
    path: .
    commands:
      install:
        status: true
        method: go build -o ./build/app ./cmd/app/main.go
      run:
        status: true
        method: ./build/app
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
