version: "3.7"
services:
  app:
    container_name: "app"
    build:
      context: ../../
      dockerfile: ./scripts/app/Dockerfile
      target: "builder"
    env_file: .env
    ports:
      - "8080:8080"
    command: ["realize", "start"]
    volumes:
      - "../../:/work"
    networks:
      - "app-net"
    depends_on:
      - "db"

  db:
    container_name: "db"
    image: "postgres:12.2-alpine"
    environment:
      - POSTGRES_USER=holo
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - "app-net"

networks:
  app-net:
    name: "app-net"
