version: "3.7"
services:
  app:
    container_name: "app"
    image: somq14/holo-back-base:0.0.1
    environment:
      - GOPATH=/work/.go-cache/source
      - GOCACHE=/work/.go-cache/build
    env_file:
      - config.env
      - secret.env
    ports:
      - "8080:8080"
    command: ["realize", "start"]
    volumes:
      - "../../:/work"
    networks:
      - "app-net"
    depends_on:
      - "db"

  db:
    container_name: "db"
    image: "postgres:12.2-alpine"
    environment:
      - POSTGRES_USER=holo
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - "app-net"

  goose:
    container_name: "goose"
    image: somq14/holo-back-base:0.0.1
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgresql://db:5432/holo?user=holo&password=password&sslmode=disable
    entrypoint: ["goose", "-dir", "migrate"]
    command: "up"
    volumes:
      - "../../:/work"
    networks:
      - "app-net"
    depends_on:
      - "app"

networks:
  app-net:
    name: "app-net"
