version: 2.1
executors:
  default:
    working_directory: /home/circleci/holo-back
    machine:
      image: ubuntu-1604:202004-01

commands:
  save_workspace:
    steps:
      - persist_to_workspace:
          root: /home/circleci/holo-back
          paths:
            - .

  load_workspace:
    steps:
      - attach_workspace:
          at: /home/circleci/holo-back

  save_gocache:
    steps:
      - run: sudo chown -R circleci:circleci .go-cache
      - save_cache:
          key: gocache-v2-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}-{{ .Revision }}
          paths:
            - .go-cache

  load_gocache:
    steps:
      - restore_cache:
          keys:
            - gocache-v2-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}-{{ .Revision }}
            - gocache-v2-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: install yarn
          command: |
            npm install -g yarn
            yarn add -D yarn
            npx yarn install
            cd ./scripts/deployment
            yarn add -D yarn
            npx yarn install
      - save_workspace

  build:
    executor: default
    steps:
      - load_workspace
      - load_gocache
      - run: cp ./scripts/test/secret.env ./scripts/app
      - run: npx yarn docker run app go build -x -o ./build/app ./cmd/app/main.go
      - run: npx yarn docker down
      - save_gocache

  lint:
    executor: default
    steps:
      - load_workspace
      - load_gocache
      - run: npx yarn lint
      - run: npx yarn test:docker down

  test:
    executor: default
    steps:
      - load_workspace
      - load_gocache
      - run: npx yarn test
      - run: npx yarn test:docker down

  deploy:
    executor: default
    steps:
      - load_workspace
      - run: cd ./scripts/deployment; npx yarn build
      - run: cd ./scripts/deployment; npx yarn deploy

  migrate:
    executor: default
    steps:
      - load_workspace
      - run: cd ./scripts/deployment; npx yarn migrate

workflows:
  version: 2
  buid_and_deploy:
    jobs:
      - setup
      - build:
          context: holo-back
          requires:
            - setup
      - lint:
          context: holo-back
          requires:
            - setup
      - test:
          context: holo-back
          requires:
            - setup
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
            - lint
            - test
      - deploy:
          context: holo-back
          requires:
            - hold
      - migrate:
          context: holo-back
          requires:
            - hold
