appname: "holo-app"
cors:
  originwhitelist:
    - "" # overlay
  headerwhitelist:
    - "*"
    - "Authorization"
googleoauth2:
  googleauthurl: "https://accounts.google.com/o/oauth2/auth"
  googletokenurl: "https://accounts.google.com/o/oauth2/token"
  googletokeninfourl: "https://oauth2.googleapis.com/tokeninfo"
  clientid: "904632099489-0cfq1s2icvrncfeu2ufk4lkivp50i60q.apps.googleusercontent.com"
  clientsecret: "" # env
  clientredirecturl: "" # overlay
  scope: "email profile openid"
youtubeclient:
  apikey: "" # env
  apiurl:
    video: "https://www.googleapis.com/youtube/v3/videos"
